title: Mantraraj Dash
description: ## Contact
- **Email:** [mantraraj.dash@gmail.com](mailto:mantraraj.dash@gmail.com)
- **LinkedIn:** [linkedin.com/in/mantraraj](https://linkedin.com/in/mantraraj)
logo: /assets/img/profile_img.png
show_downloads: False
theme: jekyll-theme-minimal
