title: Mantraraj Dash
description: > 
  Data Scientist with over 8 years of experience using ML/AI models on top of real world data to drive business value
  <br><br>
  Working currently as an Advanced Data Science Consultant at ZS Associates, based out of London, UK. 
  <br><br>
  <img align="left" width="40" src="https://raw.githubusercontent.com/mdash/mdash.github.io/dev/assets/img/contact.svg" alt="Contact">
  <a href="https://linkedin.com/in/mantraraj">LinkedIn</a> 
  <br>
  <a href="mailto:mantraraj.dash@gmail.com">Email</a> 
logo: /assets/img/profile_img.png
show_downloads: False
theme: jekyll-theme-minimal
