title: Mantraraj Dash
description: Senior Data Science and AI Leader specializing in agentic AI systems, GenAI, and ML solutions for complex real-world data.
logo: /assets/img/profile_img.png
show_downloads: false
theme: jekyll-theme-minimal
